<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Reportagens</h3>
                <i class="fa fa-list"></i> <?=$this->view->title;?><br>

                <table class="table">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Data</th>

                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                        <tr>
                            <td><?=$value['codigo'];?></td>
                            <td><?=date("d-m-Y H:i:s", $value['data']);?></td>
                            <td>
                                <a href="<?=$this->view->controller;?>detalhar/id/<?=$value['id'];?>" class="btn btn-success">
                                    <i class="fa fa-eye"></i> Detalhar
                                </a>
                                <a href="<?=$this->view->controller;?>solucionar/id/<?=$value['id'];?>" class="btn btn-primary">
                                    <i class="fa fa-legal"></i> Solucionar
                                </a>
                                <a href="#"
                                   onclick="confirmar('Deseja DESCARTAR esta reportagem?', '<?=$this->view->controller;?>descartar/id/<?=$value['id'];?>')"
                                   class="btn btn-danger">
                                    <i class="fa fa-trash"></i> Descartar
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                
                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?=$this->view->controller;?>visualizar/pagina/<?=$this->view->btn['previus'];?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                        <li><a href="<?=$this->view->controller;?>visualizar/pagina/<?=$value;?>"><?=$value;?></a></li>
                        <?php endforeach;?>
                        <li>
                            <a href="<?=$this->view->controller;?>visualizar/pagina/<?=$this->view->btn['next'];?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->