<style>
    .map {
        margin: 0px auto;
        width: 100%;
        height: 300px;
        background-color: #ddd;
        display: none;
        border: dashed 2px #c3c3c3;
    }
    .progress {
        margin: 0px auto;
        width:100%;
        border: 1px solid #ccc;
        padding: 1px;
        border-radius: 3px;
        display: none;
    }
    .bar {
        background-color: #B4F5B4;
        width:0%;
        height:20px;
        border-radius: 3px;
    }
    .percent {
        margin: 0px auto;
        display:inline-block;
        top:3px;
        left:48%;
    }
    .compartilhamento-content {
        display: inline;
    }
    form {
        display: none;
    }
</style>
<div class="starter-template">

    <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="gridModalLabel">
                    <i class="fa fa-map-marker"></i> Localização
                </h4>
            </div>
            <div class="modal-body">
                Para realizar uma denúncia, é necessário que você forneça a sua localização. Deseja compartilhar?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary compartilhar" data-dismiss="modal">Sim</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
            </div>
        </div>
      </div>
    </div>
    
    <h3><i class="fa fa-bullhorn"></i> Reportar caso</h3>
    <p class="lead">
        <div id="status"></div>
        <div id="mapholder" class="map"></div>
        
        <div class="compartilhamento-content">
            <button type="button" class="btn btn-primary compartilhar">
                <i class="fa fa-map-marker"></i> Compartilhar Localização!
            </button>
        </div>
        
        <form action="<?=APPDIR?>reportagem/novo/" method="post" enctype="multipart/form-data">
            <div class="progress">
                <div class="bar"></div >
                <div class="percent">0%</div >
            </div>
            <input type="hidden" name="lat" id="lat">
            <input type="hidden" name="lon" id="lon">
            <input type="file" name="myfile" size="45"><br>
            <input type="submit" class="btn btn-primary btn-lg" value="Reportar">
        </form>

    </p>
</div>
<script src="https://maps.google.com/maps/api/js?sensor=false"></script>
<script>
var x = document.getElementById("status");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition,showError);
    } else {
        x.innerHTML="<i class='fa  fa-warning'></i> Geolocalização não suportada neste browser.";
    }
}

function showPosition(position) {
    lat = position.coords.latitude;
    lon = position.coords.longitude;
    latImput = document.getElementById("lat");
    lonImput = document.getElementById("lon");
    latImput.value = lat;
    lonImput.value = lon;
    latlon = new google.maps.LatLng(lat, lon);
    mapholder = document.getElementById('mapholder');
    mapholder.style.width = '100%';
    mapholder.style.height = '300px';

    var myOptions = {
        center:latlon,zoom:18,
        mapTypeId:google.maps.MapTypeId.ROADMAP,
        mapTypeControl:false,
        navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL}
    };
    var map = new google.maps.Map(document.getElementById("mapholder"),myOptions);
    var marker = new google.maps.Marker({position:latlon,map:map,title:"Você está aqui"});
}

function showError(error) {
    switch (error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML="<i class='fa  fa-warning'></i> Usuário rejeitou a solicitação de Geolocalização.";
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML="<i class='fa  fa-warning'></i> Localização indisponível.";
            break;
        case error.TIMEOUT:
            x.innerHTML="<i class='fa  fa-warning'></i> O tempo da requisição expirou.";
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML="<i class='fa  fa-warning'></i> Algum erro desconhecido aconteceu.";
            break;
    }
}
</script>
