<style>
    .map {
        margin: 0px auto;
        width: 100%;
        height: 300px;
        background-color: #f0ad4e;
        display: inline-block;
        border: dashed 2px #FF7A00;
    }
    .progress {
        margin: 0px auto;
        width:100%;
        border: 1px solid #ddd;
        padding: 1px;
        border-radius: 3px;
    }
    .bar {
        background-color: #B4F5B4;
        width:0%;
        height:20px;
        border-radius: 3px;
    }
    .percent {
        margin: 0px auto;
        display:inline-block;
        top:3px;
        left:48%;
    }
</style>
<div class="starter-template">

    <h3><i class="fa fa-bullhorn"></i> Reportar caso</h3>
    <p class="lead">
        <div id="status"></div>
        <div id="mapholder" class="map"></div>
        <form action="<?=APPDIR?>reportagem/novo/" method="post" enctype="multipart/form-data">
            <div class="progress">
                <div class="bar"></div >
                <div class="percent">0%</div >
            </div>
            <input type="hidden" name="lat" id="lat">
            <input type="hidden" name="lon" id="lon">
            <input type="file" name="myfile" size="45"><br>
            <input type="submit" class="btn btn-primary btn-lg" value="Reportar">
        </form>

    </p>
</div>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script>
var x = document.getElementById("status");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition,showError);
    } else {
        x.innerHTML="<i class='fa  fa-warning'></i> Geolocalização não suportada neste browser.";
    }
}

function showPosition(position) {
    lat = position.coords.latitude;
    lon = position.coords.longitude;
    latImput = document.getElementById("lat");
    lonImput = document.getElementById("lon");
    latImput.value = lat;
    lonImput.value = lon;
    latlon = new google.maps.LatLng(lat, lon);
    mapholder = document.getElementById('mapholder');
    mapholder.style.width = '100%';
    mapholder.style.height = '300px';

    var myOptions = {
        center:latlon,zoom:18,
        mapTypeId:google.maps.MapTypeId.ROADMAP,
        mapTypeControl:false,
        navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL}
    };
    var map = new google.maps.Map(document.getElementById("mapholder"),myOptions);
    var marker = new google.maps.Marker({position:latlon,map:map,title:"Você está aqui"});
}

function showError(error) {
    switch (error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML="<i class='fa  fa-warning'></i> Usuário rejeitou a solicitação de Geolocalização.";
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML="<i class='fa  fa-warning'></i> Localização indisponível.";
            break;
        case error.TIMEOUT:
            x.innerHTML="<i class='fa  fa-warning'></i> O tempo da requisição expirou.";
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML="<i class='fa  fa-warning'></i> Algum erro desconhecido aconteceu.";
            break;
    }
}
getLocation();
</script>
