<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Coleta</h3>
                <i class="fa fa-list"></i> <?=$this->view->title;?><br>
                <a href="<?=$this->view->controller;?>novo/" class="btn btn-info">
                    <i class="fa fa-asterisk"></i> Novo Registro
                </a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Material</th>
                            <th>UF</th>
                            <th>Qtd Coletada</th>
                            <th>Qtd Restante</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                        <tr>
                            <td><?=$value['tipo'] . ' - ' . $value['caracteristica'];?></td>
                            <td><?=$value['uf'];?></td>
                            <td><?=$value['quantidade_inicial'];?></td>
                            <td><?=$value['quantidade_distribuida'];?></td>
                            <td>
                                <a href="#"
                                   onclick="confirmar('Deseja CANCELAR esta coleta?', '<?=$this->view->controller;?>cancelar/id/<?=$value['id'];?>')"
                                   class="btn btn-danger">
                                    <i class="fa fa-trash"></i> Cancelar
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                
                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?=$this->view->controller;?>visualizar/pagina/<?=$this->view->btn['previus'];?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                        <li><a href="<?=$this->view->controller;?>visualizar/pagina/<?=$value;?>"><?=$value;?></a></li>
                        <?php endforeach;?>
                        <li>
                            <a href="<?=$this->view->controller;?>visualizar/pagina/<?=$this->view->btn['next'];?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->