<!DOCTYPE html>
<html lang="pt-br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Bruno Monteiro">

    <title>
        <?php
            echo isset($this->view->title)? $this->view->title : '' ;
            echo ' :: '.APPNAM.' '.APPVER.' ::';
        ?>    
    </title>

    <!-- Bootstrap Core CSS -->
    <link href="<?=ATTACH;?>bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?=ATTACH;?>metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?=DIRCSS;?>sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?=ATTACH;?>font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=APPDIR;?>"><?=APPNAM.' '.APPVER;?></a>
            </div>
            <!-- /.navbar-header -->

            <?php include_once ATTPAG.'menu_horizontal_top.phtml'; ?>

            <?php include_once ATTPAG.'menu_vertical.phtml'; ?>
        </nav>

            <?=$this->content();?> 

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="<?=ATTACH;?>jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?=ATTACH;?>bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?=ATTACH;?>metisMenu/dist/metisMenu.min.js"></script>

    <!-- Mask Plugin JavaScript -->
    <script src="<?=ATTACH;?>jqueryMask/jquery.mask.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="<?=DIRJS_;?>sb-admin-2.js"></script>
    <!-- Script padrão de envio de formulário -->
    <script type="text/javascript">
        function resetForm(){
            document.getElementById("form").reset();
            setInterval("clearMsg()",2000);
        }
        function clearMsg(){
            $("#resultado").empty();            
        }
        function focusOn(idCampo){
            //document.getElementsById( nameCampo ).focus();
            document.getElementById( idCampo ).focus();
        }
        function confirmar(texto, url){
            if(confirm(texto)){
                window.location = url;
            }
        }
        function mudarTipoDoc(tipo) {
            if (tipo == 1) {
                $(document).ready(function() {
                    $('#cnpj_cpf').mask('00.000.000/0000-00', {reverse: true});
                });
            } else {
                $(document).ready(function() {
                    $('#cnpj_cpf').mask('000.000.000-00', {reverse: true});
                });
            }
        }
        mudarTipoDoc(1);
        $(document).ready(function() {
            $('#form').submit(function() { 
                var dados = $(this).serialize();
                $("#resultado").html("<i class='fa fa-spinner fa-pulse fa-3x fa-fw'></i> Enviando...<span class='sr-only'>Enviando...</span>");
                $.ajax({
                    type: "POST", // Tipo de metodo
                    url: $(this).attr("action"), //Recebe o valor da action do form
                    data: dados,
                    success: function(data) //Se tiver sucesso...
                    {
                        $("#resultado").html(data);
                    }
                });
                return false;
            });
            //Requisita                           
        });
    </script>

</body>

</html>

