<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?=$this->view->title?></h5>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?=$this->view->controller;?>registra/" method="post" id="form">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Mterial Coletado</label>
                                    <select id="coletas_id"
                                            name="coletas_id"
                                            class="form-control"
                                            required>
                                        <?php foreach ($this->view->resultColeta as $value): ?>
                                        <option value="<?=$value['id'];?>">
                                            (<?=$value['quantidade'] . $value['uf'];?>) <?=$value['tipo'];?> - <?=$value['caracteristica'];?>
                                        </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Cooperativa</label>
                                    <select id="cooperativas_id"
                                            name="cooperativas_id"
                                            class="form-control"
                                            required>
                                        <?php foreach ($this->view->resultCooperativa as $value): ?>
                                        <option value="<?=$value['id'];?>">
                                            <?=$value['sigla'];?>
                                        </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>

                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Quantidade</label>
                                    <input type="text"
                                           id="quantidade"
                                           name="quantidade"
                                           placeholder="Quantidade a ser distribuida"
                                           class="form-control"
                                           maxlength="4"
                                           required>
                                </div>
                                <div class="form-group">
                                    <br>
                                    <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                    <a href="<?=$this->view->controller;?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                </div>

                            </div>
                        </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->