            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <a href="<?=APPDIR;?>"><i class="fa fa-home fa-fw"></i> Home</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bullhorn fa-fw"></i> Reportagem<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?=APPDIR;?>reportagem/"><i class="fa fa-newspaper-o fa-fw"></i> Listar Reportagens</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-truck fa-fw"></i> Distribuição de Material<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?=APPDIR;?>distribuicao/novo/"><i class="fa fa-plus-circle fa-fw"></i> Nova Distribuição</a>
                                </li>
                                <li>
                                    <a href="<?=APPDIR;?>distribuicao/"><i class="fa fa-list-ol fa-fw"></i> Listar Distribuições</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-university fa-fw"></i> Cooperativas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?=APPDIR;?>cooperativa/novo/"><i class="fa fa-plus-circle fa-fw"></i> Novo Registro</a>
                                </li>
                                <li>
                                    <a href="<?=APPDIR;?>cooperativa/"><i class="fa fa-cogs fa-fw"></i> Gerenciar Cooperativas</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-recycle fa-fw"></i> Coletas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?=APPDIR;?>coleta/novo/"><i class="fa fa-plus-circle fa-fw"></i> Novo Registro</a>
                                </li>
                                <li>
                                    <a href="<?=APPDIR;?>coleta/"><i class="fa fa-list-ol fa-fw"></i> Listar Coleta</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-list-ul fa-fw"></i> Tipos de Materias<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?=APPDIR;?>material/novo/"><i class="fa fa-plus-circle fa-fw"></i> Novo Registro</a>
                                </li>
                                <li>
                                    <a href="<?=APPDIR;?>material/"><i class="fa fa-cogs fa-fw"></i> Gerenciar Material</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-users fa-fw"></i> Usuários<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?=APPDIR;?>acesso/novo/"><i class="fa fa-plus-circle fa-fw"></i> Novo Registro</a>
                                </li>
                                <li>
                                    <a href="<?=APPDIR;?>acesso/"><i class="fa fa-cogs fa-fw"></i> Gerenciar Usuários</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?=APPDIR;?>acesso/logout/"><i class="fa fa-remove fa-fw"></i> Sair</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->