<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?=$this->view->title?></h5>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Edição
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?=$this->view->controller;?>altera/" method="post" id="form">
                            <input type="hidden" name="id" value="<?=$this->view->result['id'];?>">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Sigla</label>
                                    <input type="text"
                                           id="sigla"
                                           name="sigla"
                                           placeholder="Sigla da Cooperativa"
                                           class="form-control"
                                           maxlength="20"
                                           value="<?=$this->view->result['sigla'];?>"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label>Nome</label>
                                    <input type="text"
                                           id="nome"
                                           name="nome"
                                           placeholder="Nome da Cooperativa"
                                           class="form-control"
                                           maxlength="50"
                                           value="<?=$this->view->result['nome'];?>"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label>Tipo de Documando:</label>
                                    <label class="radio-inline">
                                        <input type="radio"
                                               name="tipo_doc"
                                               id="tipo_doc"
                                               value="1"
                                               onchange="mudarTipoDoc(1)"
                                               <?=$this->view->result['tipo_doc'] == 1 ? 'checked="checked"' : '';?> > CNPJ |
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio"
                                               name="tipo_doc"
                                               id="tipo_doc"
                                               value="2"
                                               onchange="mudarTipoDoc(2)"
                                               <?=$this->view->result['tipo_doc'] == 2 ? 'checked="checked"' : '';?> > CPF
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label>CNPJ/CPF</label>
                                    <input type="text"
                                           id="cnpj_cpf"
                                           name="cnpj_cpf"
                                           placeholder="Indique o CNPJ da Cooperativa ou CPF do reponsável"
                                           class="form-control"
                                           maxlength="18"
                                           value="<?=$this->view->result['cnpj_cpf'];?>"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label>Responsável</label>
                                    <input type="text"
                                           id="responsavel_nome"
                                           name="responsavel_nome"
                                           placeholder="Nome do responsável pela cooperativa"
                                           class="form-control"
                                           maxlength="50"
                                           value="<?=$this->view->result['responsavel_nome'];?>"
                                           required>
                                </div>

                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Endereço</label>
                                    <input type="text"
                                           id="endereco"
                                           name="endereco"
                                           placeholder="Endereço da cooperativa"
                                           class="form-control"
                                           maxlength="128"
                                           value="<?=$this->view->result['endereco'];?>"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label>Fone Fixo</label>
                                    <input type="text"
                                           id="fone_fixo"
                                           name="fone_fixo"
                                           placeholder="Número do telefone fixo para contato (apenas números)"
                                           class="form-control"
                                           maxlength="10"
                                           value="<?=$this->view->result['fone_fixo'];?>"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label>FoneCelular</label>
                                    <input type="text"
                                           id="fone_celular"
                                           name="fone_celular"
                                           placeholder="Número do telefone celular para contato (apenas números)"
                                           class="form-control"
                                           maxlength="11"
                                           value="<?=$this->view->result['fone_celular'];?>"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="text"
                                           id="email"
                                           name="email"
                                           placeholder="E-mail para contato"
                                           class="form-control"
                                           maxlength="50"
                                           value="<?=$this->view->result['email'];?>">
                                </div>


                                <div class="form-group">
                                    <br>
                                    <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                    <a href="<?=$this->view->controller;?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                </div>

                            </div>
                        </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<script>
    setInterval("mudarTipoDoc(<?=$this->view->result['tipo_doc'] == 1 ?  : 2;?>)",200);
</script>